spring:
  profiles:
    active: "dev"
    group:
      test: test,debug,local #,localdb
      dev: develop,debug,local,localdb
      prod: production,local
  application:
    name: "makalu_hrm"
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        type: trace
    ROOT: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
      cors:
        allowed-origins: '*'



