spring:
  banner:
    location: classpath:/banners/dev.txt
  devtools:
    restart:
      enabled: true

makalu:
  network:
    ip: 0:0:0:0:0:0:0:1



  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true



